from pathlib import Path

import pytest

from appenv import UvVersion

def strip_ansi_codes(text: str) -> str: ...

class MockUvBin:
    base: Path
    bin: Path
    _version: UvVersion
    def __init__(self) -> None: ...
    @property
    def version(self) -> UvVersion: ...
    def cmd(self, args: list[str], verbose: bool = ..., **kwargs: object) -> str: ...

@pytest.fixture(autouse=True)
def disable_argparse_colors(monkeypatch) -> None: ...
@pytest.fixture
def workdir(tmp_path: Path) -> Path: ...
@pytest.fixture
def test_settings(tmp_path: Path): ...
@pytest.fixture
def mock_uv() -> MockUvBin: ...
@pytest.fixture(autouse=True)
def mock_uv_version(monkeypatch, request) -> None: ...
@pytest.fixture
def subprocess_run_fail(monkeypatch) -> None: ...
@pytest.fixture
def app_env(test_settings): ...
@pytest.fixture
def make_mock_uv(): ...
@pytest.fixture
def no_ensure_python(monkeypatch) -> None: ...
@pytest.fixture
def mock_cmd_python(monkeypatch) -> None: ...
@pytest.fixture
def create_venv(tmp_path: Path): ...
@pytest.fixture
def mock_uv_lock(monkeypatch) -> None: ...
@pytest.fixture
def mock_logdir(tmp_path: Path, monkeypatch) -> Path: ...
@pytest.fixture
def clean_uv_project_env() -> None: ...
@pytest.fixture
def make_pyproject(): ...
@pytest.fixture
def capture_appenv_logs(): ...
