from pathlib import Path

import pytest

from appenv import UvVersion

class MockUvBin:
    base: Path
    bin: Path
    _version: UvVersion
    def __init__(self) -> None: ...
    @property
    def version(self) -> UvVersion: ...
    def cmd(self, args: list[str], verbose: bool = ..., **kwargs: object) -> str: ...

@pytest.fixture(autouse=True)
def disable_argparse_colors(monkeypatch): ...
@pytest.fixture
def workdir(tmp_path: Path) -> Path: ...
@pytest.fixture
def test_settings(tmp_path: Path): ...
@pytest.fixture
def mock_uv(): ...
@pytest.fixture(autouse=True)
def mock_uv_version(monkeypatch, request): ...
@pytest.fixture
def subprocess_run_fail(monkeypatch): ...
