def test_ensure_best_python_skips_when_env_set(
    tmp_path, monkeypatch, make_pyproject
): ...
def test_ensure_best_python_already_running_best(
    tmp_path, monkeypatch, make_pyproject
): ...
def test_ensure_best_python_execv_with_correct_args(
    monkeypatch, tmp_path, make_pyproject
): ...
def test_ensure_best_python_respects_upper_bound(
    tmp_path, monkeypatch, capsys, make_pyproject
): ...
def test_ensure_best_python_exits_65_no_python_found(
    monkeypatch, tmp_path, capsys, make_pyproject
) -> None: ...
def test_ensure_best_python_exits_65_with_upper_bound(
    monkeypatch, tmp_path, capsys, make_pyproject
): ...
def test_ensure_best_python_default_min_version(
    tmp_path, monkeypatch, make_pyproject
): ...
def test_ensure_best_python_broken_python(tmp_path, monkeypatch, make_pyproject): ...
