from pathlib import Path

ROOT: Path

def test_file_cleanup_deleted_files_not_present() -> None: ...
def test_flat_toctree_index_has_toctree() -> None: ...
def test_flat_toctree_lists_all_content_files() -> None: ...
def test_flat_toctree_conf_suppress_warnings_only_myst() -> None: ...
def test_factual_corrections_pyi_has_exit_code_usage() -> None: ...
def test_factual_corrections_no_appenv_profiling_in_readme() -> None: ...
def test_factual_corrections_no_specs_dir_in_index() -> None: ...
def test_factual_corrections_correct_uv_commands_in_index() -> None: ...
def test_factual_corrections_exit_code_usage_in_commands() -> None: ...
def test_factual_corrections_exit_code_usage_in_architecture() -> None: ...
def test_factual_corrections_pyi_stub_claim_corrected() -> None: ...
def test_run_command_removal_no_run_command_in_commands_doc() -> None: ...
def test_python_version_statement_nuance_in_index() -> None: ...
def test_quick_start_rewrite_prompt_text_matches_source() -> None: ...
def test_quick_start_rewrite_dependency_is_httpie() -> None: ...
