def test_migrate_uses_python_preference_from_requirements(
    tmp_path, monkeypatch, capsys, test_settings
): ...
def test_migrate_existing_symlinks(tmp_path, monkeypatch, capsys, test_settings): ...
def test_migrate_empty_dependencies(tmp_path, monkeypatch, capsys, test_settings): ...
def test_migrate_uses_directory_name(
    tmp_path, monkeypatch, capsys, test_settings
) -> None: ...
def test_migrate_already_exists(
    tmp_path, monkeypatch, capsys, patterns, test_settings
) -> None: ...
def test_migrate_no_requirements_txt(
    workdir, monkeypatch, capsys, patterns, test_settings
) -> None: ...
def test_migrate_editable_missing_package_warns(
    tmp_path, monkeypatch, capsys, patterns, test_settings
): ...
def test_migrate_editable_git_url_warns(
    tmp_path, monkeypatch, capsys, patterns, test_settings
): ...
def test_migrate_editable_mixed_valid_and_invalid(
    tmp_path, monkeypatch, capsys, patterns, test_settings
): ...
def test_migrate_editable_warnings_updated(
    tmp_path, monkeypatch, capsys, patterns, test_settings
): ...
def test_migrate_existing_pyproject_no_project_section(
    tmp_path, monkeypatch, capsys, patterns, test_settings
): ...
