def test_init_fresh_start_interactive(
    tmp_path, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_init_fresh_start_default_dependencies(
    tmp_path, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_init_empty_command_name_uses_app(
    workdir, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_init_unlink_broken_symlink(
    workdir, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_init_already_exists(workdir, monkeypatch, capsys, test_settings) -> None: ...
def test_init_empty_command_name_defaults_to_app(
    workdir, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_init_with_path_creates_directory(
    tmp_path, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_init_with_nested_path_creates_directories(
    tmp_path, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_init_with_existing_directory(
    tmp_path, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_init_without_path_uses_current_directory(
    tmp_path, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_init_appenv_script_already_exists(
    workdir, monkeypatch, capsys, test_settings, mock_uv
): ...
