def strip_ansi_codes(text): ...
def _setup_pyproject_project(workdir, name="ducker", deps=None): ...
def test_update_lockfile_pyproject_workflow(
    workdir, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_update_lockfile_verbose_output(
    workdir, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_update_lockfile_no_changes_output(
    workdir, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_update_lockfile_pyproject_diff_mode(
    workdir, monkeypatch, capsys, tmp_path, test_settings, mock_uv
): ...
def test_update_lockfile_pyproject_no_changes(
    workdir, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_update_lockfile_pyproject_updated(
    workdir, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_update_lockfile_pyproject_diff_verbose(
    workdir, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_update_lockfile_pyproject_diff_no_changes(
    workdir, monkeypatch, capsys, test_settings, mock_uv
): ...
def test_update_lockfile_pyproject_calls_uv_lock(
    tmp_path, monkeypatch, test_settings, mock_uv
): ...
def test_update_lockfile_verbose_shows_running_uv_lock(
    tmp_path, monkeypatch, capsys, test_settings, mock_uv
): ...
