from collections.abc import Callable
from pathlib import Path

import pytest
from pytest import CaptureFixture, LogCaptureFixture, MonkeyPatch
from pytest_patterns.plugin import PatternsLib

from appenv import AppEnv

from .conftest import MockUvBin

def test_main_shows_usage_without_subcommand(
    monkeypatch: MonkeyPatch,
    capsys: CaptureFixture[str],
    tmp_path: Path,
    no_ensure_python: None,
    mock_logdir: Path,
) -> None: ...
def test_grouped_help_formatter_skips_command_not_in_choices() -> None: ...
def test_main_shows_grouped_help(
    monkeypatch: MonkeyPatch,
    capsys: CaptureFixture[str],
    tmp_path: Path,
    patterns: PatternsLib,
    no_ensure_python: None,
    mock_logdir: Path,
) -> None: ...
def test_help_same_as_no_args(
    monkeypatch: MonkeyPatch,
    capsys: CaptureFixture[str],
    tmp_path: Path,
    no_ensure_python: None,
    mock_logdir: Path,
) -> None: ...
def test_main_clears_pythonpath(
    monkeypatch: MonkeyPatch, no_ensure_python: None
) -> None: ...
def test_main_calls_run_when_not_appenv(
    monkeypatch: MonkeyPatch, tmp_path: Path, no_ensure_python: None
) -> None: ...
def test_main_calls_meta_when_appenv(
    monkeypatch: MonkeyPatch, no_ensure_python: None
) -> None: ...
def test_cmd_with_string_uses_shell() -> None: ...
def test_cmd_raises_value_error_on_failure() -> None: ...
def test_cmd_with_list_no_shell() -> None: ...
@pytest.mark.no_mock_uv_version
def test_ensure_uv_returns_uvbin_from_path(
    monkeypatch: MonkeyPatch, tmp_path: Path
) -> None: ...
def test_meta_calls_reset(
    monkeypatch: MonkeyPatch, tmp_path: Path, app_env: Callable[..., AppEnv]
) -> None: ...
def test_meta_calls_prepare(
    monkeypatch: MonkeyPatch, tmp_path: Path, app_env: Callable[..., AppEnv]
) -> None: ...
def test_meta_calls_python(
    monkeypatch: MonkeyPatch, tmp_path: Path, app_env: Callable[..., AppEnv]
) -> None: ...
def test_meta_calls_run_script(
    monkeypatch: MonkeyPatch, tmp_path: Path, app_env: Callable[..., AppEnv]
) -> None: ...
def test_run_sets_env_and_execs(
    monkeypatch: MonkeyPatch,
    tmp_path: Path,
    app_env: Callable[..., AppEnv],
    make_pyproject: Callable[..., None],
) -> None: ...
def test_run_missing_binary_shows_helpful_error(
    monkeypatch: MonkeyPatch,
    tmp_path: Path,
    capsys: CaptureFixture[str],
    app_env: Callable[..., AppEnv],
    patterns: PatternsLib,
) -> None: ...
def test_python_method_calls_run(
    monkeypatch: MonkeyPatch, tmp_path: Path, app_env: Callable[..., AppEnv]
) -> None: ...
def test_print_colored_diff_returns_true_when_changes(
    capsys: CaptureFixture[str],
) -> None: ...
def test_print_colored_diff_returns_false_when_no_changes(
    capsys: CaptureFixture[str],
) -> None: ...
@pytest.mark.no_mock_uv_version
def test_ensure_uv_returns_uvbin_on_success(
    monkeypatch: MonkeyPatch, tmp_path: Path, capsys: CaptureFixture[str]
) -> None: ...
def test_parse_uv_version_parses_correctly() -> None: ...
def test_parse_uv_version_handles_two_parts() -> None: ...
def test_parse_uv_version_returns_zero_on_invalid() -> None: ...
def test_parse_uv_version_strips_v_prefix() -> None: ...
def test_find_available_pythons_sorting(monkeypatch: MonkeyPatch) -> None: ...
def test_find_available_pythons_bare_python3_fallback(
    monkeypatch: MonkeyPatch,
) -> None: ...
def test_find_available_pythons_bare_python3_deduplication(
    monkeypatch: MonkeyPatch,
) -> None: ...
def test_find_available_pythons_bare_python3_too_old(
    monkeypatch: MonkeyPatch,
) -> None: ...
def test_find_available_pythons_bare_python3_subprocess_fails(
    monkeypatch: MonkeyPatch,
) -> None: ...
def test_version_satisfies_constraints_min_only() -> None: ...
def test_version_satisfies_constraints_with_max() -> None: ...
def test_version_satisfies_constraints_edge_cases() -> None: ...
def test_run_script_delegates(
    capsys: CaptureFixture[str], tmp_path: Path, app_env: Callable[..., AppEnv]
) -> None: ...
def test_show_version(
    tmp_path: Path,
    capsys: CaptureFixture[str],
    patterns: PatternsLib,
    app_env: Callable[..., AppEnv],
) -> None: ...
def test_pyproject_requires_python_edge_cases(tmp_path: Path) -> None: ...
def test_pyproject_requires_python_with_upper_bound(tmp_path: Path) -> None: ...
def test_main_calls_ensure_best_python(
    monkeypatch: MonkeyPatch, workdir: Path
) -> None: ...
def test_main_entry_point_subprocess() -> None: ...
def test_version_consistency() -> None: ...
def test_convert_version_preference_empty_versions() -> None: ...
def test_lockfile_content_missing_file(tmp_path: Path) -> None: ...
def test_uv_version_unknown() -> None: ...
def test_uv_version_str_zero() -> None: ...
def test_pyproject_builder_merges_with_existing_content(tmp_path: Path) -> None: ...
def test_uv_sync_with_extras(
    tmp_path: Path, monkeypatch: MonkeyPatch, make_mock_uv: Callable[..., MockUvBin]
) -> None: ...
def test_ensure_pyproject_no_project_section_no_requirements(
    tmp_path: Path, monkeypatch: MonkeyPatch, capsys: CaptureFixture[str]
) -> None: ...
def test_ensure_pyproject_no_file_with_requirements(
    tmp_path: Path, monkeypatch: MonkeyPatch, capsys: CaptureFixture[str]
) -> None: ...
def test_cmd_error_output_not_quiet(capsys: CaptureFixture[str]) -> None: ...
def test_colored_caller_formatter_format() -> None: ...
def test_setup_logging_verbose(tmp_path: Path, caplog: LogCaptureFixture) -> None: ...
def test_pyproject_python_preference_empty_after_filter(
    tmp_path: Path, capsys: CaptureFixture[str]
) -> None: ...
def test_print_migration_info_skips_minimum_version_with_single_python(
    tmp_path: Path, capsys: CaptureFixture[str]
) -> None: ...
def test_migrate_single_python_version(
    tmp_path: Path, capsys: CaptureFixture[str]
) -> None: ...
def test_init_skips_appenv_script_creation(
    tmp_path: Path,
    monkeypatch: MonkeyPatch,
    capsys: CaptureFixture[str],
    app_env: Callable[..., AppEnv],
) -> None: ...
def test_remove_path_directory(tmp_path: Path) -> None: ...
def test_remove_path_nonexistent(tmp_path: Path) -> None: ...
def test_grouped_help_formatter_truncates_long_help() -> None: ...
def test_run_missing_binary_empty_venv(
    monkeypatch: MonkeyPatch,
    tmp_path: Path,
    capsys: CaptureFixture[str],
    app_env: Callable[..., AppEnv],
) -> None: ...
def test_meta_unrecognized_arguments(
    tmp_path: Path, app_env: Callable[..., AppEnv], capsys: CaptureFixture[str]
) -> None: ...
def test_ensure_gitignore_returns_early_when_all_entries_exist(
    tmp_path: Path, capsys: CaptureFixture[str]
) -> None: ...
