import pytest

def test_main_shows_usage_without_subcommand(
    monkeypatch, capsys, tmp_path, no_ensure_python, mock_logdir
): ...
def test_grouped_help_formatter_skips_command_not_in_choices() -> None: ...
def test_main_shows_grouped_help(
    monkeypatch, capsys, tmp_path, patterns, no_ensure_python, mock_logdir
): ...
def test_help_same_as_no_args(
    monkeypatch, capsys, tmp_path, no_ensure_python, mock_logdir
): ...
def test_main_clears_pythonpath(monkeypatch, no_ensure_python): ...
def test_main_calls_run_when_not_appenv(monkeypatch, tmp_path, no_ensure_python): ...
def test_main_calls_meta_when_appenv(monkeypatch, no_ensure_python): ...
def test_cmd_with_string_uses_shell() -> None: ...
def test_cmd_raises_value_error_on_failure() -> None: ...
def test_cmd_with_list_no_shell() -> None: ...
@pytest.mark.no_mock_uv_version
def test_ensure_uv_returns_uvbin_from_path(monkeypatch, tmp_path): ...
def test_meta_calls_reset(monkeypatch, tmp_path, app_env): ...
def test_meta_calls_prepare(monkeypatch, tmp_path, app_env): ...
def test_meta_calls_python(monkeypatch, tmp_path, app_env): ...
def test_meta_calls_run_script(monkeypatch, tmp_path, app_env): ...
def test_run_sets_env_and_execs(
    monkeypatch, tmp_path, app_env, make_pyproject
): ...
def test_run_missing_binary_shows_helpful_error(
    monkeypatch, tmp_path, capsys, app_env, patterns
): ...
def test_python_method_calls_run(monkeypatch, tmp_path, app_env): ...
def test_print_colored_diff_returns_true_when_changes(capsys) -> None: ...
def test_print_colored_diff_returns_false_when_no_changes(capsys) -> None: ...
@pytest.mark.no_mock_uv_version
def test_ensure_uv_returns_uvbin_on_success(monkeypatch, tmp_path, capsys): ...
def test_parse_uv_version_parses_correctly() -> None: ...
def test_parse_uv_version_handles_two_parts() -> None: ...
def test_parse_uv_version_returns_zero_on_invalid() -> None: ...
def test_parse_uv_version_strips_v_prefix() -> None: ...
def test_find_available_pythons_sorting(monkeypatch): ...
def test_find_available_pythons_bare_python3_fallback(monkeypatch): ...
def test_find_available_pythons_bare_python3_deduplication(monkeypatch): ...
def test_find_available_pythons_bare_python3_too_old(monkeypatch): ...
def test_find_available_pythons_bare_python3_subprocess_fails(monkeypatch): ...
def test_version_satisfies_constraints_min_only() -> None: ...
def test_version_satisfies_constraints_with_max() -> None: ...
def test_version_satisfies_constraints_edge_cases() -> None: ...
def test_run_script_delegates(capsys, tmp_path, app_env): ...
def test_show_version(tmp_path, capsys, patterns, app_env): ...
def test_pyproject_requires_python_edge_cases(tmp_path) -> None: ...
def test_pyproject_requires_python_with_upper_bound(tmp_path) -> None: ...
def test_ensure_best_python_skips_when_env_set(tmp_path, monkeypatch) -> None: ...
def test_ensure_best_python_default_min_version(tmp_path, monkeypatch): ...
def test_ensure_best_python_already_running_best(tmp_path, monkeypatch): ...
def test_ensure_best_python_broken_python(tmp_path, monkeypatch): ...
def test_main_calls_ensure_best_python(monkeypatch, workdir): ...
def test_main_entry_point_subprocess() -> None: ...
def test_version_consistency() -> None: ...
def test_convert_version_preference_empty_versions() -> None: ...
def test_lockfile_content_missing_file(tmp_path) -> None: ...
def test_uv_version_unknown() -> None: ...
def test_uv_version_str_zero() -> None: ...
def test_pyproject_builder_merges_with_existing_content(tmp_path) -> None: ...
def test_uv_sync_with_extras(tmp_path, monkeypatch, make_mock_uv): ...
def test_ensure_pyproject_no_project_section_no_requirements(
    tmp_path, monkeypatch, capsys
) -> None: ...
def test_ensure_pyproject_no_file_with_requirements(
    tmp_path, monkeypatch, capsys
) -> None: ...
def test_cmd_error_output_not_quiet(capsys) -> None: ...
def test_colored_caller_formatter_format() -> None: ...
def test_setup_logging_verbose(tmp_path, caplog) -> None: ...
def test_pyproject_python_preference_empty_after_filter(tmp_path, capsys) -> None: ...
def test_print_migration_info_skips_minimum_version_with_single_python(
    tmp_path, capsys
) -> None: ...
def test_migrate_single_python_version(tmp_path, capsys) -> None: ...
def test_init_skips_appenv_script_creation(
    tmp_path, monkeypatch, capsys, app_env
): ...
def test_remove_path_directory(tmp_path) -> None: ...
def test_remove_path_nonexistent(tmp_path) -> None: ...
def test_grouped_help_formatter_truncates_long_help() -> None: ...
def test_run_missing_binary_empty_venv(
    monkeypatch, tmp_path, capsys, app_env
): ...
def test_meta_unrecognized_arguments(tmp_path, app_env, capsys): ...
def test_ensure_gitignore_returns_early_when_all_entries_exist(
    tmp_path, capsys
) -> None: ...
