def test_reset_nonexisting_envdir_silent(tmp_path, test_settings): ...
def test_reset_removes_envdir_with_subdirs(tmp_path, test_settings): ...
def test_reset_removes_venv(tmp_path, capsys, test_settings): ...
def test_reset_removes_both_venv_and_appenv(tmp_path, capsys, test_settings): ...
def test_reset_unlinks_file_in_appenv(workdir, monkeypatch, capsys) -> None: ...
def test_reset_removes_venv_symlink(
    workdir, monkeypatch, capsys, test_settings
) -> None: ...
def test_reset_removes_real_venv(
    workdir, monkeypatch, capsys, test_settings
) -> None: ...
def test_reset_removes_old_venv_directory(
    workdir, monkeypatch, capsys, test_settings
) -> None: ...
def test_reset_keeps_uv_binary(
    tmp_path, monkeypatch, capsys, test_settings
) -> None: ...
