import pytest

def test_uv_bin_cmd_raises_when_uv_not_found(monkeypatch) -> None: ...
def test_try_uv_from_path_returns_path_when_valid(monkeypatch, tmp_path): ...
def test_try_uv_from_path_returns_none_when_invalid_version(monkeypatch): ...
def test_try_uv_from_path_returns_none_when_not_in_path(monkeypatch): ...
@pytest.mark.no_mock_uv_version
def test_uv_binget_uv_version_returns_version_on_success(tmp_path, monkeypatch): ...
@pytest.mark.no_mock_uv_version
def test_uv_binget_uv_version_not_valid_on_subprocess_error(
    monkeypatch, capsys
) -> None: ...
@pytest.mark.no_mock_uv_version
def test_uv_binget_uv_version_returns_none_when_too_old(monkeypatch, capsys): ...
@pytest.mark.no_mock_uv_version
def test_uv_binget_uv_version_handles_parse_error(tmp_path, monkeypatch, capsys): ...
@pytest.mark.no_mock_uv_version
def test_uv_binget_uv_version_index_error_on_split(monkeypatch, capsys): ...
def test_try_uv_from_appenv_dir_returns_path_when_valid(monkeypatch, tmp_path): ...
def test_try_uv_from_appenv_dir_returns_none_when_invalid_version(
    monkeypatch, tmp_path
): ...
def test_try_uv_from_appenv_dir_returns_none_when_not_exists(
    monkeypatch, tmp_path
) -> None: ...
def test_try_uv_from_nix_channel_returns_path_when_valid(
    monkeypatch, tmp_path, caplog
): ...
def test_try_uv_from_nix_channel_returns_path_when_created(
    monkeypatch, tmp_path, caplog
): ...
def test_try_uv_from_nix_channel_returns_none_when_nix_not_found(
    monkeypatch, tmp_path
) -> None: ...
def test_try_uv_from_nix_channel_returns_none_when_build_fails(
    monkeypatch, tmp_path, caplog, subprocess_run_fail
) -> None: ...
def test_try_uv_from_nix_channel_returns_none_when_invalid_version(
    monkeypatch, tmp_path, caplog
): ...
def test_try_uv_from_nix_channel_and_appenv_dir_share_same_path(
    monkeypatch, tmp_path, caplog
): ...
def test_try_uv_from_nix_flake_returns_path_when_valid(
    monkeypatch, tmp_path, caplog
): ...
def test_try_uv_from_nix_flake_returns_none_when_build_fails(
    monkeypatch, tmp_path, caplog, subprocess_run_fail
) -> None: ...
def test_try_uv_from_nix_flake_returns_none_when_invalid_version(
    monkeypatch, tmp_path, caplog
): ...
def test_try_uv_from_pip_returns_path_when_valid(monkeypatch, tmp_path, caplog): ...
def test_try_uv_from_pip_returns_none_when_ensurepip_fails(
    monkeypatch, tmp_path, caplog
): ...
def test_try_uv_from_pip_returns_none_when_pip_install_fails(
    monkeypatch, tmp_path, caplog
): ...
def test_try_uv_from_pip_returns_none_when_invalid_version(
    monkeypatch, tmp_path, caplog
): ...
def test_get_uv_bin_returns_from_nix_channel_when_previous_fail(
    monkeypatch, tmp_path
): ...
def test_get_uv_bin_returns_from_nix_flake_when_previous_fail(
    monkeypatch, tmp_path
): ...
def test_get_uv_bin_returns_from_pip_when_previous_fail(monkeypatch, tmp_path): ...
def test_uv_bin_cmd_verbose_flag_and_output(monkeypatch, caplog): ...
@pytest.mark.no_mock_uv_version
def test_uv_bin_pip_fallback_raises_error(tmp_path, monkeypatch): ...
def test_cleanup_appenv_uv_with_base_and_existing_dir(tmp_path) -> None: ...
def test_get_uv_bin_returns_from_appenv_dir_when_path_fails(monkeypatch, tmp_path): ...
@pytest.mark.no_mock_uv_version
def test_ensure_uv_invalid_version(tmp_path, monkeypatch, capsys): ...
