from pathlib import Path

from pytest import MonkeyPatch

def _pip_is_available() -> bool: ...
def _sys_python_has_pip() -> bool: ...
def test_pip_install_uv_creates_working_binary(tmp_path: Path) -> None: ...
def test_pip_install_uv_from_which_pip(tmp_path: Path) -> None: ...
def test_try_uv_from_pip_integration(
    tmp_path: Path, monkeypatch: MonkeyPatch
) -> None: ...
