from pathlib import Path

import pytest
from pytest import CaptureFixture

def _uv_is_runnable() -> bool: ...
def setup_isolated_appenv(tmp_path: Path) -> Path: ...
def test_init_cli(tmp_path: Path) -> None: ...
def test_migrate_cli(tmp_path: Path) -> None: ...
@pytest.mark.slow(reason="Installs httpie package, takes ~10 seconds")
def test_bootstrap_flow_like_readme(
    tmp_path: Path, capsys: CaptureFixture[str]
) -> None: ...
def test_prepare_cli(tmp_path: Path) -> None: ...
def test_prepare_cli_no_pyproject(tmp_path: Path) -> None: ...
def test_prepare_cli_no_lockfile(tmp_path: Path) -> None: ...
