import ast
from pathlib import Path

import pytest

TESTS_DIR: Path

def _collect_py_modules(root: Path) -> list[Path]: ...
def _get_function_defs(source: str) -> list[ast.FunctionDef]: ...
def _get_function_names(source: str) -> set[str]: ...
@pytest.mark.xfail(reason="phase-2")
def test_complete_stub_coverage() -> None: ...
@pytest.mark.xfail(reason="phase-2")
def test_stub_sync_function_count() -> None: ...
@pytest.mark.xfail(reason="phase-2")
def test_no_phantom_functions() -> None: ...
@pytest.mark.xfail(reason="phase-2")
def test_fixture_parameter_typing() -> None: ...
@pytest.mark.xfail(reason="phase-2")
def test_specific_new_stubs_exist() -> None: ...
@pytest.mark.xfail(reason="phase-2")
def test_specific_updated_stubs_sync() -> None: ...
