from pathlib import Path
from typing import Any

REPO_ROOT: Path
E2E_YML: Path
INSTALLATION_MD: Path
ARCHITECTURE_MD: Path

def _load_e2e_yaml() -> Any: ...
def test_init_e2e_coverage_bookworm_pip_uses_printf_init() -> None: ...
def test_python39_e2e_job_exists() -> None: ...
def test_python39_e2e_uses_bullseye_container() -> None: ...
def test_python39_e2e_requires_python_39() -> None: ...
def test_installation_md_mentions_auto_download() -> None: ...
def test_installation_md_links_to_architecture() -> None: ...
def test_architecture_md_has_six_discovery_steps() -> None: ...
def test_architecture_md_has_platform_detection_section() -> None: ...
def test_architecture_md_platform_detection_has_triple_table() -> None: ...
