"""Type stubs for appenv."""

import argparse
from pathlib import Path

REQUIREMENTS_TXT: str
REQUIREMENTS_LOCK: str

class TColors:
    """Terminal colors for pretty output."""

    RED: str
    GREEN: str
    YELLOW: str
    RESET: str

def cmd(
    c: str | list[str], *, merge_stderr: bool = True, quiet: bool = False
) -> bytes: ...
def has_uv() -> bool: ...
def python(
    path: Path, c: list[str], *, merge_stderr: bool = True, quiet: bool = False
) -> bytes: ...
def uv_cmd(
    args: list[str], *, merge_stderr: bool = True, quiet: bool = False
) -> bytes: ...
def parse_preferences() -> list[str] | None: ...
def ensure_venv(target: Path) -> None: ...
def find_minimal_python() -> str | None: ...
def ensure_best_python(base: Path) -> None: ...
def main() -> None: ...

class AppEnv:
    base: Path
    appenv_dir: Path
    original_cwd: Path

    def __init__(self, base: Path, original_cwd: Path) -> None: ...
    def meta(self) -> None: ...
    def run(self, command: str, argv: list[str]) -> None: ...
    def prepare(
        self,
        args: argparse.Namespace | None = None,
        remaining: list[str] | None = None,
    ) -> str: ...
    def init(
        self,
        args: argparse.Namespace | None = None,
        remaining: list[str] | None = None,
    ) -> None: ...
    def python(self, args: argparse.Namespace, remaining: list[str]) -> None: ...
    def run_script(self, args: argparse.Namespace, remaining: list[str]) -> None: ...
    def reset(
        self,
        args: argparse.Namespace | None = None,
        remaining: list[str] | None = None,
    ) -> None: ...
    def update_lockfile(
        self,
        args: argparse.Namespace | None = None,
        remaining: list[str] | None = None,
    ) -> None: ...
    def _assert_requirements_lock(self) -> None: ...
    def _hash_requirements(self) -> str: ...
