"""Type stubs for appenv."""

import argparse
from pathlib import Path

REQUIREMENTS_TXT: str
REQUIREMENTS_LOCK: str
PYPROJECT_TOML: str
UV_LOCK: str

_uv_bin_cache: str | None

class TColors:
    """Terminal colors for pretty output."""

    RED: str
    GREEN: str
    YELLOW: str
    RESET: str

def cmd(
    c: str | list[str],
    *,
    merge_stderr: bool = True,
    quiet: bool = False,
    cwd: str | None = None,
) -> bytes: ...
def has_nix() -> bool: ...
def verbose_print(*args, **kwargs) -> None: ...
def get_uv_bin(base: Path | None = None) -> str: ...
def ensure_uv(base: Path) -> None: ...
def python(
    path: Path, c: list[str], *, merge_stderr: bool = True, quiet: bool = False
) -> bytes: ...
def uv_cmd(
    args: list[str],
    verbose: bool = False,
    **kwargs,
) -> bytes: ...
def parse_preferences() -> list[str] | None: ...
def ensure_venv(target: Path, base: Path | None = None) -> None: ...
def find_minimal_python() -> str | None: ...
def ensure_best_python(base: Path) -> None: ...
def detect_project_type(base: Path) -> str | None: ...
def parse_requires_python(pyproject_path: Path) -> str | None: ...
def find_available_pythons() -> list[tuple[str, str]]: ...
def ensure_best_python_for_pyproject(base: Path) -> None: ...
def parse_uv_version(version_str: str) -> tuple[int, int, int]: ...
def check_uv_version() -> tuple[int, int, int]: ...
def ensure_uv_version() -> None: ...
def main() -> None: ...

class AppEnv:
    base: Path
    appenv_dir: Path
    original_cwd: Path

    def __init__(self, base: Path, original_cwd: Path) -> None: ...
    def meta(self) -> None: ...
    def run(self, command: str, argv: list[str]) -> None: ...
    def prepare(
        self,
        args: argparse.Namespace | None = None,
        remaining: list[str] | None = None,
    ) -> str: ...
    def init(
        self,
        args: argparse.Namespace | None = None,
        remaining: list[str] | None = None,
    ) -> None: ...
    def init_pyproject(
        self,
        args: argparse.Namespace | None = None,
        remaining: list[str] | None = None,
    ) -> None: ...
    def python(self, args: argparse.Namespace, remaining: list[str]) -> None: ...
    def run_script(self, args: argparse.Namespace, remaining: list[str]) -> None: ...
    def show_version(
        self,
        args: argparse.Namespace | None = None,
        remaining: list[str] | None = None,
    ) -> None: ...
    def reset(
        self,
        args: argparse.Namespace | None = None,
        remaining: list[str] | None = None,
    ) -> None: ...
    def update_lockfile(
        self,
        args: argparse.Namespace | None = None,
        remaining: list[str] | None = None,
    ) -> None: ...
    def _assert_requirements_lock(self) -> None: ...
    def _hash_requirements(self) -> str: ...
    def _prepare_pyproject(self) -> Path: ...
    def _prepare_requirements(self) -> Path: ...
    def _update_lockfile_pyproject(self, args: argparse.Namespace | None) -> None: ...
    def _update_lockfile_requirements(
        self, args: argparse.Namespace | None
    ) -> None: ...
