import argparse
import logging
from argparse import Namespace
from dataclasses import dataclass
from pathlib import Path
from typing import Final, NamedTuple

__version__: Final[str]

log: logging.Logger

# Exit codes (BSD sysexits.h conventions)
EXIT_CODE_DATAERR: Final[int]
EXIT_CODE_NOINPUT: Final[int]
EXIT_CODE_UNAVAILABLE: Final[int]
EXIT_CODE_USAGE: Final[int]

# Format constants
MAX_HELP_TEXT_LENGTH: Final[int]
VERSION_PARTS_COUNT: Final[int]

class GroupedHelpFormatter(argparse.HelpFormatter):
    def _format_action(self, action: argparse.Action) -> str: ...

class RequirementsTxtInfo(NamedTuple):
    dependencies: list[str]
    editable_dependencies: list[str]
    python_versions: list[str]

def convert_version_preference(versions: list[str]) -> tuple[str, list[str]]: ...
def version_satisfies_constraints(
    version: str, min_version: str, max_version: str | None = None
) -> bool: ...
def remove_path(path: Path) -> None: ...

class Pyproject:
    path: Path
    requirements_path: Path
    def __init__(self, base: Path) -> None: ...
    @property
    def content(self) -> str: ...
    def migrate_from_requirements_txt(self) -> Pyproject: ...
    @property
    def requires_python(self) -> tuple[str | None, str | None]: ...
    @property
    def exists(self) -> bool: ...
    @property
    def has_project_section(self) -> bool: ...
    @property
    def can_be_created_from_requirements_txt(self) -> bool: ...
    @property
    def requirements_txt_info(self) -> RequirementsTxtInfo: ...
    def print_migration_info(self) -> None: ...
    def _parse_requirements_file(self) -> RequirementsTxtInfo: ...
    def _parse_python_preference(self) -> list[str]: ...
    def _generate_content_with_project(
        self,
        project_name: str,
        description: str,
        dependencies: list[str],
        requires_python: str,
    ) -> str: ...
    def with_project_section(
        self,
        project_name: str,
        description: str,
        dependencies: list[str],
        requires_python: str = ">=3.10",
    ) -> Pyproject: ...

def create_pyproject(
    target: Path,
    project_name: str,
    description: str,
    dependencies: list[str],
    python_version: str,
) -> Pyproject: ...

class LockFile:
    path: Path
    def __init__(self, base: Path) -> None: ...
    @property
    def exists(self) -> bool: ...
    @property
    def content(self) -> str: ...
    def diff(self, uv_bin: UvBin, base: Path, verbose: bool) -> str: ...
    def diff_summary(self, old_lines: set[str]) -> str: ...
    def read_lockfile_lines(self) -> set[str]: ...

@dataclass(order=True, frozen=True)
class UvVersion:
    major: int
    minor: int
    patch: int
    def __str__(self) -> str: ...
    @property
    def valid(self) -> bool: ...
    @staticmethod
    def unknown() -> UvVersion: ...
    @staticmethod
    def minimum() -> UvVersion: ...
    @staticmethod
    def from_string(version_str: str) -> UvVersion: ...

class UvBin:
    appenv_dir: Path
    bin: Path
    uv_dir: Path
    managed_uv: Path
    def __init__(self, appenv_dir: Path) -> None: ...
    def cmd(
        self,
        args: list[str],
        *,
        verbose: bool = False,
        **kwargs: object,
    ) -> str: ...
    @property
    def version(self) -> UvVersion: ...
    @staticmethod
    def get_uv_version(uv_path: Path) -> UvVersion: ...
    def _get_uv_bin(self) -> Path: ...
    def _try_uv_from_path(self) -> Path | None: ...
    def _try_uv_from_appenv_dir(self) -> Path | None: ...
    def _try_uv_from_nix_channel(self) -> Path | None: ...
    def _try_uv_from_nix_flake(self) -> Path | None: ...
    def _try_uv_from_pip(self) -> Path | None: ...
    def _cleanup_appenv_uv(self) -> None: ...

class NoValidUvError(RuntimeError): ...

@dataclass(frozen=True)
class AppEnvSettings:
    verbose: bool
    extras: list[str]
    basedir: Path

class AppEnv:
    appenv_dir: Path
    appenv_script: Path
    base: Path
    log_dir: Path
    original_cwd: Path
    settings: AppEnvSettings
    venv_link: Path
    venv_python: Path
    venv_real: Path
    def __init__(self, original_cwd: Path, settings: AppEnvSettings) -> None: ...
    def run(self, command: str, argv: list[str]) -> None: ...
    # appenv itself and its sub-commands
    def meta(
        self, remaining_args: list[str] | None = None, prog: str = "appenv"
    ) -> None: ...
    def prepare(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> Path: ...
    def init(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> None: ...
    def migrate(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> None: ...
    def python(self, args: Namespace, remaining: list[str]) -> None: ...
    def run_script(self, args: Namespace, remaining: list[str]) -> None: ...
    def run_uv(self, args: Namespace, remaining: list[str]) -> None: ...
    def show_version(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> None: ...
    def reset(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> None: ...
    def update_lockfile(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> None: ...
    def self_update(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> None: ...
    # Helpers
    def _ensure_appenv_script(self, *, update: bool = False) -> None: ...
    def _uv_lock(self, uv: UvBin, diff: bool) -> str: ...
    def _uv_sync(self, *, dev_mode: bool, uv: UvBin) -> None: ...
    def _set_up_logdir(self) -> Path: ...
    def _prepare_venv(self, dev_mode: bool) -> Path: ...
    def _set_up_command_symlink(
        self,
        command_name: str,
        project_name: str,
    ) -> None: ...
    def _prepare_appenv_dir(self) -> None: ...
    def _chdir_to_project(self, target: Path) -> None: ...
    @staticmethod
    def _extract_version(script: Path) -> str | None: ...

def ensure_uv(appenv_dir: Path) -> UvBin: ...
def ensure_pyproject(base: Path) -> Pyproject: ...
def ensure_lock_file(base: Path) -> LockFile: ...
def ensure_gitignore(base: Path, entries: list[str]) -> None: ...
def cmd(
    c: str | list[str],
    *,
    merge_stderr: bool = ...,
    quiet: bool = ...,
    cwd: str | None = ...,
) -> bytes: ...
def ensure_best_python(base: Path) -> None: ...
def find_available_pythons() -> list[tuple[str, str]]: ...
def print_colored_diff(
    old_content: str, new_content: str, fromfile: str, tofile: str
) -> bool: ...
def appenv_settings_from_env() -> AppEnvSettings: ...

class ColoredCallerFormatter(logging.Formatter):
    dim: str
    reset: str
    def format(self, record: logging.LogRecord) -> str: ...

def setup_logging(command_name: str, log_dir: Path, verbose: bool) -> None: ...
def main() -> None: ...
